name: Documentation Action

on:
  workflow_call:
    inputs:
      deploy:
        description: "Optional flag to deploy documentation"
        required: false
        type: boolean
        default: true
      default-branch:
        description: "Optional default branch to target for release"
        required: false
        type: string
        default: "main"
      runs-on:
        description: "Optional label for the runner to run on"
        required: false
        type: string
        default: "['self-hosted', 'Linux', 'X64']"
      node-version:
        description: "Optional Node.js version to use"
        required: false
        type: string
        default: "21.x"
      working-directory:
        description: "Optional working directory"
        required: false
        type: string
        default: "docs"
      committer-email:
        description: "Optional committer email"
        required: false
        type: string
        default: "47529956+alwyn974@users.noreply.github.com"
      committer-name:
        description: "Optional committer user/name"
        required: false
        type: string
        default: "alwyn974"

jobs:
  build:
    name: Build Documentation
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    permissions:
      contents: write
      id-token: write
    env:
      node-version: ${{ inputs.node-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # ratchet:pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js ${{ env.node-version }}
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: ${{ env.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: |
          pnpm install

      - name: Build documentation
        working-directory: ${{ inputs.working-directory }}
        run: |
          pnpm build

      - name: Deploy documentation
        if: github.event_name != 'pull_request' && inputs.deploy == true && (startsWith(github.ref, 'refs/tags/docs-v') || github.ref == format('refs/heads/{0}', inputs.default-branch))
        working-directory: ${{ inputs.working-directory }}
        env:
          GIT_USER: ${{ inputs.committer-name }}
          GIT_USER_NAME: ${{ inputs.committer-name }}
          GIT_USER_EMAIL: ${{ inputs.committer-email }}
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm run deploy
