name: Todo Action

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Optional label for the runner to run on"
        required: false
        type: string
        default: "self-hosted"
      MANUAL_COMMIT_REF:
        description: "The SHA of the commit to get the diff for"
        required: false
        type: string
      MANUAL_BASE_REF:
        description: "By default, the commit entered above is compared to the one directly before it; to go back further, enter an earlier SHA here"
        required: false
        type: string

jobs:
  todo-issues:
    name: Run Todo Issues
    runs-on: ${{ inputs.runs-on }}
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Manually importing TODO to Issues
        if: github.event_name == 'workflow_dispatch'
        uses: alstr/todo-to-issue-action@4120fdbb02461dd1abf18756a7464b8e45347863 # ratchet:alstr/todo-to-issue-action@v4
        env:
          MANUAL_COMMIT_REF: ${{ inputs.MANUAL_COMMIT_REF }}
          MANUAL_BASE_REF: ${{ inputs.MANUAL_BASE_REF }}
        with:
          ISSUE_TEMPLATE: |
            Todo: `{{ title }}` found in {{ url }}

            {{ body }}

            ---
            {{ snippet }}
            ---

            ##### This issue was generated by [todo-to-issue-action](https://github.com/alstr/todo-to-issue-action)

      - name: Importing TODO to Issues
        if: github.event_name != 'workflow_dispatch'
        uses: alstr/todo-to-issue-action@4120fdbb02461dd1abf18756a7464b8e45347863 # ratchet:alstr/todo-to-issue-action@v4
        with:
          AUTO_ASSIGN: true
          ISSUE_TEMPLATE: |
            Todo: `{{ title }}` found in {{ url }}

            {{ body }}

            ---
            {{ snippet }}
            ---

            ##### This issue was generated by [todo-to-issue-action](https://github.com/alstr/todo-to-issue-action)
